### PR TITLE
Add a .gitignore

### PR DESCRIPTION
**Pull request by kellend-git**
Add a .gitignore to start consistent with http://www.dartlang.org/tools/private-files.html

### CODE REVIEW

**Comment by vsmenon** [comment]
Thanks!

**Comment by bholt** [comment]
Why is `bin` ignored? This makes changes to the start compiler not get added...

**Comment by vsmenon** [comment]
Yeah, you're right.  I just updated to fix this.

**Comment by bholt** [comment]
There's one other piece, which is to ignore `bin/packages`. It's in my pull request.

**Comment by vsmenon** [comment]
Have you updated it yet?  I just see '# bin' in your pull request.

**Comment by bholt** [comment]
I also delete the `/` after "packages", which makes it match any "packages" directory, including `bin/packages`.

**Pull request merged**
